### ISSUE TITLE
Create Board component

### ISSUE THREAD

**Issue by TazDeCoder** [TazDeCoder/battleship#1]
This component will be used to display the board for the players to interact with.

### Tasks:
- [x] **Render 10x10 grid** - not including row/column headers
- [x] **Render 'x' marker when either player has successfully "hit" a part of a ship piece** 
- [ ] **Render 5 different ship pieces** - initially invisible and only visible when they are marked on, or game has finished
- [ ] **Add handlers to deal with game logic; for instance when a board piece is toggled**

If you are unfamiliar with this game - [please check out this link](https://en.wikipedia.org/wiki/Battleship_(game)).

**Note:** these are only some practical guidelines, so feel free to add any more necessary if you like
